// This file is auto-generated by scripts/generate-projects.cjs
// Do not edit this file directly.
// Edit the markdown files in public/projects/ instead.

import { Project } from '../../types';

export const DESIGN_DATA: Project[] = [
  {
    id: 'd1',
    star: true,
    common: {
      category: 'Graphics & UI',
      image: 'https://www.figma.com/file/cRFVFLypB290MP6ImMgiPd/thumbnail?ver=thumbnails/86fca228-9e5a-4b50-bc1e-8bb31f33edb9',
      figmaUrl: 'https://www.figma.com/design/cRFVFLypB290MP6ImMgiPd/%E5%A4%A7%E5%B9%BF%E8%B5%9B-%7C-%E5%8D%B3%E6%97%B6%E8%AE%BE%E8%AE%A1-%E5%BE%81%E8%BE%B0%C2%B7HMI%E6%99%BA%E8%83%BD%E5%BA%A7%E8%88%B1%E8%AE%BE%E8%AE%A1?node-id=55-2&t=7dPgyLMJDD32pFp4-1',
      gallery: [
        'https://picsum.photos/800/600?random=11',
        'https://picsum.photos/800/600?random=12',
        'https://picsum.photos/800/600?random=13',
      ],
    },
    zh: {
      title: '视觉设计系统 | 征辰 HMI 设计',
      subtitle: 'UI/UX 设计',
      description: '新能源汽车的人机交互界面设计。采用玻璃拟态和柔和渐变的"视觉减重"系统。',
      role: 'UI 设计师',
      tags: ['汽车', 'HMI', 'Figma'],
      roleDetail: "独立完成从中控大屏到仪表盘的整套UI绘制与交互逻辑设计。",
      concept: "参考了很多车载HMI的设计，我决定设计一款视觉减重的系统：信息更加明确，配色更清新，提升驾驶者的舒适感。我参考了很多风格，比如扁平化。但我认为，在汽车这种强调即时与准确反馈的环境，交互系统视觉上需要一个强反馈感的设计。于是毛玻璃与轻拟物化成为了我的最终选择。",
      awards: ['课程设计优秀作品'],
    },
    en: {
      title: 'HMI | Pilgrimage HMI System',
      subtitle: 'UI/UX Design',
      description: 'HMI design for New Energy Vehicles (NEV). A "Visual Weight Reduction" system featuring glassmorphism and soft gradients.',
      role: 'UI Designer',
      tags: ['Automotive', 'HMI', 'Figma'],
      roleDetail: "Independently completed the entire UI drawing and interaction logic from the central screen to the dashboard.",
      concept: "I designed a Visual Weight Reduction system: clearer information, fresher colors, improving driver comfort. I believed that in a car environment emphasizing immediate feedback, the interface needed strong visual feedback. Thus, glassmorphism and light skeuomorphism became my choice.",
      awards: ['Course Design Excellence Award'],
    }
  }
];
