// This file is auto-generated by scripts/generate-articles.cjs
// Do not edit this file directly.
// Edit the markdown files in public/articles/ instead.

import { ArticleCategory, Language } from '../../types';

export interface ArticlesPageContent {
  title: string;
  description: string;
}

export const ARTICLES_PAGE_DATA: Record<Language, ArticlesPageContent> = {
  zh: {
    title: '文章',
    description: '个人思考、学习分享与生活记录。'
  },
  en: {
    title: 'Articles',
    description: 'Thoughts, learning journey, and life records.'
  }
};

export const ARTICLE_DATA = [
  {
    "id": "3be1759918813393b2bd84edd2c5df87",
    "common": {
      "category": "瞎叨be叨",
      "link": "/articles/测试-LaTeX渲染测试.md",
      "date": "2026-02-20",
      "isLocal": true,
      "tags": [
        "测试",
        "LaTeX",
        "数学公式"
      ],
      "star": false
    },
    "zh": {
      "title": "LaTeX 渲染测试"
    },
    "en": {
      "title": "LaTeX 渲染测试"
    }
  },
  {
    "id": "0bd0bbbac4f03e3e0e3e539c5e0a8b83",
    "common": {
      "category": "瞎叨be叨",
      "link": "/articles/安全杂谈-AI篇001：醉语风险与防护（drunk ai）.md",
      "date": "2026-02-11",
      "isLocal": true,
      "tags": [
        "网络安全",
        "AI",
        "AI安全",
        "LLM安全",
        "博客",
        "公众号"
      ],
      "coverImage": "https://cdn.jsdelivr.net/gh/klopiop/Picture/blog/%E5%AE%89%E5%85%A8%E6%9D%82%E8%B0%88-AI%E7%AF%87_001%EF%BC%9A%E9%86%89%E8%AF%AD%E9%A3%8E%E9%99%A9%E4%B8%8E%E9%98%B2%E6%8A%A4%EF%BC%88drunk%20ai%EF%BC%89.png",
      "star": false
    },
    "zh": {
      "title": "安全杂谈-AI篇001：醉语风险与防护（drunk ai）"
    },
    "en": {
      "title": "安全杂谈-AI篇001：醉语风险与防护（drunk ai）"
    }
  },
  {
    "id": "3845544d2d4a22d94cc17038bcf855c4",
    "common": {
      "category": "瞎叨be叨",
      "link": "/articles/技术解读-AI篇001：claude skills【一场AI的洪流】.md",
      "date": "2026-02-11",
      "isLocal": true,
      "tags": [
        "人工智能",
        "AI",
        "claude",
        "技术解读",
        "博客",
        "公众号"
      ],
      "coverImage": "https://cdn.jsdelivr.net/gh/klopiop/Picture/blog/%E6%8A%80%E6%9C%AF%E8%A7%A3%E8%AF%BB-AI%E7%AF%87001%EF%BC%9Aclaude%20skills%E3%80%90%E4%B8%80%E5%9C%BAAI%E7%9A%84%E6%B4%AA%E6%B5%81%E3%80%91.png",
      "star": false
    },
    "zh": {
      "title": "技术解读-AI篇001：claude skills【一场AI的洪流】"
    },
    "en": {
      "title": "技术解读-AI篇001：claude skills【一场AI的洪流】"
    }
  },
  {
    "id": "d597fb3a46ed6f81cc6438225c33d825",
    "common": {
      "category": "瞎叨be叨",
      "link": "/articles/技术解读-AI篇002：多Agent的风波.md",
      "date": "2026-02-11",
      "isLocal": true,
      "tags": [
        "人工智能",
        "AI",
        "技术解读",
        "博客",
        "公众号",
        "MultiAgent"
      ],
      "coverImage": "https://cdn.jsdelivr.net/gh/klopiop/Picture/blog/%E6%8A%80%E6%9C%AF%E8%A7%A3%E8%AF%BB-AI%E7%AF%87002%EF%BC%9A%E5%A4%9AAgent%E7%9A%84%E9%A3%8E%E6%B3%A2-cover.png",
      "star": false
    },
    "zh": {
      "title": "技术解读-AI篇002：多Agent的风波"
    },
    "en": {
      "title": "技术解读-AI篇002：多Agent的风波"
    }
  },
  {
    "id": "bd622cd264fece90144a14f36a38a8e3",
    "common": {
      "category": "瞎叨be叨",
      "link": "/articles/实战技术-开发篇001：一切的源头“GIT”.md",
      "date": "2026-01-23",
      "isLocal": true,
      "tags": [
        "开发",
        "前置基础",
        "git",
        "博客",
        "公众号"
      ],
      "star": false
    },
    "zh": {
      "title": "实战技术-开发篇001：一切的源头“GIT”"
    },
    "en": {
      "title": "实战技术-开发篇001：一切的源头“GIT”"
    }
  }
];
