// This file is auto-generated by scripts/generate-articles.cjs
// Do not edit this file directly.
// Edit the markdown files in public/articles/ instead.

import { ArticleCategory, Language } from '../../types';

export interface ArticlesPageContent {
  title: string;
  description: string;
}

export const ARTICLES_PAGE_DATA: Record<Language, ArticlesPageContent> = {
  zh: {
    title: '文章',
    description: '个人思考、学习分享与生活记录。'
  },
  en: {
    title: 'Articles',
    description: 'Thoughts, learning journey, and life records.'
  }
};

export const ARTICLE_DATA = [
  {
    "id": "40c2cd6b500160f38752242d11dedee4",
    "common": {
      "category": "瞎叨be叨",
      "link": "/articles/article4.md",
      "date": "2024-01-22",
      "isLocal": true,
      "tags": [
        "markdown",
        "cover",
        "example",
        "landscape"
      ],
      "coverImage": "https://images.unsplash.com/photo-1503614472-8c93d56e92ce?q=80&w=1000&auto=format&fit=crop",
      "star": false
    },
    "zh": {
      "title": "带封面的Markdown文章示例"
    },
    "en": {
      "title": "带封面的Markdown文章示例"
    }
  },
  {
    "id": "b6d93871f41dc05452c50f642718bfff",
    "common": {
      "category": "瞎叨be叨",
      "link": "/articles/article3.md",
      "date": "2023-10-03",
      "isLocal": true,
      "tags": [
        "data structures",
        "algorithms",
        "programming"
      ],
      "star": false
    },
    "zh": {
      "title": "数据结构简介"
    },
    "en": {
      "title": "数据结构简介"
    }
  },
  {
    "id": "27d5b15f57ef97537a73e51189d8d2ad",
    "common": {
      "category": "瞎叨be叨",
      "link": "/articles/article2.md",
      "date": "2023-10-02",
      "isLocal": true,
      "tags": [
        "react",
        "javascript",
        "frontend"
      ],
      "star": false
    },
    "zh": {
      "title": "React组件示例"
    },
    "en": {
      "title": "React组件示例"
    }
  },
  {
    "id": "80a2ca1e68250b93bc3e67d9ca1b6ba9",
    "common": {
      "category": "瞎叨be叨",
      "link": "/articles/article1.md",
      "date": "2023-10-01",
      "isLocal": true,
      "tags": [
        "markdown",
        "tutorial",
        "example"
      ],
      "star": true
    },
    "zh": {
      "title": "Markdown示例文章1"
    },
    "en": {
      "title": "Markdown示例文章1"
    }
  }
];
